export { default as always } from "./always";
export { default as ascend } from "./ascend";
export { default as compose } from "./compose";
export { default as converge } from "./converge";
export { default as curry, curry2, curry3, curry4, curry5 } from "./curry";
export { default as descend } from "./descend";
export { default as F } from "./F";
export { default as identity } from "./identity";
export { default as pipe } from "./pipe";
export { default as T } from "./T";
export { default as tap } from "./tap";
export { default as thunkify } from "./thunkify";
